import LoadingState from './LoadingState';
import Select from './Select';
import { useEffect, useState } from 'react';
import { api } from './cloud';
import { Field } from './ui';
import { Bell } from 'lucide-react';
type Preferences={mode:'off'|'daily'|'gentle';timezone:string;hour:number;available:boolean};
export default function EmailPreferences(){
 const [value,setValue]=useState<Preferences|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('');
 useEffect(()=>{void api<Preferences>('/account/email-preferences').then(p=>setValue({...p,timezone:p.timezone==='UTC'?Intl.DateTimeFormat().resolvedOptions().timeZone:p.timezone})).catch(()=>setError('Email preferences could not be opened.'));},[]);
 async function save(){if(!value)return;setBusy(true);setError('');setNotice('');try{setValue(await api<Preferences>('/account/email-preferences',{method:'PUT',body:value}));setNotice(value.mode==='off'?'Reminder emails are off.':'Your email preferences are saved.');}catch(e){setError(e instanceof Error?e.message:'Preferences could not be saved.');}finally{setBusy(false);}}
 return <section className="settings-reminders"><div className="settings-reminder-heading"><span className="settings-icon"><Bell size={19}/></span><div><h3>Email reminders</h3><p>Optional check-ins, on your schedule.</p></div>{value&&!value.available&&<span className="settings-badge">Coming soon</span>}</div>{!value&&!error&&<LoadingState layout="inline" label="Loading email preferences"/>}{value&&!value.available?<p className="settings-reminder-off">Reminders are off. We’ll let you choose when they’re ready.</p>:value&&<><Field label="Budget reminders"><Select value={value.mode} onChange={e=>setValue({...value,mode:e.target.value as Preferences['mode']})}><option value="off">No reminder emails</option><option value="daily" disabled={!value.available}>Daily budget review</option><option value="gentle" disabled={!value.available}>When I haven’t recorded spending</option></Select></Field>{value.mode!=='off'&&<><div className="field-grid"><Field label="Send around"><Select value={value.hour} onChange={e=>setValue({...value,hour:Number(e.target.value)})}>{Array.from({length:24},(_,hour)=><option key={hour} value={hour}>{String(hour).padStart(2,'0')}:00</option>)}</Select></Field><Field label="Time zone"><input value={value.timezone} maxLength={100} onChange={e=>setValue({...value,timezone:e.target.value})}/></Field></div><p className="small muted">{value.mode==='gentle'?'After three days without logging spending, at most once a week.':'One review email per day.'} Every reminder has an unsubscribe link. Saving enables the schedule you chose.</p></>}<p className="settings-caption">No balances, amounts or payee names in reminder emails. Security emails are separate.</p><button className="button secondary" disabled={busy} onClick={()=>void save()}>{busy?'Saving…':'Save email preferences'}</button></>}{notice&&<p role="status" className="cloud-notice">{notice}</p>}{error&&<p role="alert" className="form-error">{error}</p>}</section>;
}
