import {useConfirmation} from './Confirmation';
import LoadingState from './LoadingState';
import {useEffect,useRef,useState} from 'react';
import type {RefObject} from 'react';
import {ArrowLeft,CheckCircle2,ChevronRight,Clock3,House,Plane,Plus,Receipt,Users,X} from 'lucide-react';
import {api,getBudget} from './cloud';
import type {CloudBudget} from './cloud';
import {cents,money,today} from './engine';
import {previewSharedBudget} from './shared-budget';
import {Field,Modal} from './ui';
import Select from './Select';
import DatePicker from './DatePicker';
import {PersonAvatar} from './PeopleOverview';
import type {GroupDetail,GroupInvitation,GroupSummary,SharedChange} from './group-types';
import {changeNames} from './group-types';
import type {GroupBillSeries} from './group-types';
import {GroupBillComposer,GroupBillReview,GroupBillSections,billDraftKey} from './GroupBills';
import {useSharedRequest} from './useSharedRequest';
import {SharedChangeComposer,SharedChangeReview,changeDraftKey} from './SharedChangeReview';
import type {ChangeDraft} from './SharedChangeReview';
import './expense-groups.css';
import {useSharingFormDraft,removeSharingDraft} from './sharing-drafts';

type Form={kind:'create'}|{kind:'join';group:GroupSummary}|{kind:'purchase'}|{kind:'member'}|{kind:'change';draft:ChangeDraft}|{kind:'review';id:string}|{kind:'bill-review';id:string}|{kind:'series';series?:GroupBillSeries};
type Request=ReturnType<typeof useSharedRequest>;

export default function ExpenseGroups({snapshot,onSaved,blocked,selected,onSelect,scope,onExpense,initialReview,onReviewClosed}:{
 scope:string;snapshot:CloudBudget;onSaved:(value:CloudBudget)=>void;blocked:RefObject<boolean>;selected:string;onSelect:(id:string)=>void;onExpense:(groupId:string,expenseId:string)=>void;initialReview?:string;onReviewClosed:()=>void;
}){
 const confirm=useConfirmation();
 const [groups,setGroups]=useState<GroupSummary[]|null>(null),[detail,setDetail]=useState<GroupDetail|null>(null),[reviews,setReviews]=useState<SharedChange[]>([]),[error,setError]=useState(''),[form,setForm]=useState<Form|null>(initialReview?{kind:'review',id:initialReview}:null),[invite,setInvite]=useState<GroupInvitation|null>(null),[notice,setNotice]=useState('');
 const request=useSharedRequest(snapshot,onSaved,blocked,scope),sequence=useRef(0);
 async function load(clearError=false){
  if(clearError)setError('');
  const current=++sequence.current;
  try{
   const list=await api<{groups:GroupSummary[];changes:SharedChange[]}>('/expense-groups');
   const group=selected?await api<GroupDetail>('/expense-groups/'+selected):null;
   if(current!==sequence.current)return;
   setGroups(list.groups);setReviews(list.changes);setDetail(group);setError('');
   const latest=await getBudget(snapshot.id);if(current===sequence.current&&latest.revision>snapshot.revision)onSaved(latest);
  }catch(error){if(current===sequence.current)setError(error instanceof Error?error.message:'Groups could not be loaded.');}
 }
 useEffect(()=>{if(request.recovered?.group)onSelect(request.recovered.group.id);if(request.recovered?.change)setForm({kind:'review',id:request.recovered.change.id});if(request.recovered?.bill){onSelect(request.recovered.bill.groupId);setForm({kind:'bill-review',id:request.recovered.bill.id});}if(request.recovered?.series){setNotice('Schedule saved.');void load();}if(request.recovered?.expense){setNotice('The saved bill was confirmed.');void load();}},[request.recovered]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),6000);return()=>clearTimeout(timer);},[notice]);
 useEffect(()=>{setDetail(null);void load(true);return()=>{sequence.current++;};},[selected]);
 useEffect(()=>{if(initialReview)setForm({kind:'review',id:initialReview});},[initialReview]);
 useEffect(()=>{const timer=setInterval(()=>{if(!document.hidden&&!form&&!request.pending)void load();},5000);return()=>clearInterval(timer);},[selected,form,request.pending,snapshot.revision]);
 const close=()=>{if(!request.canClose())return;if(form?.kind==='bill-review')removeSharingDraft(scope,'group-bill-review-'+form.id);if(form?.kind==='create')removeSharingDraft(scope,'create-group');if(form?.kind==='purchase'){removeSharingDraft(scope,'group-purchase-'+selected);removeSharingDraft(scope,billDraftKey(selected));}if(form?.kind==='series')removeSharingDraft(scope,billDraftKey(selected,form.series,true));if(form?.kind==='member')removeSharingDraft(scope,'group-member-'+selected);if(form?.kind==='change')removeSharingDraft(scope,changeDraftKey(form.draft));setForm(null);onReviewClosed();void load();};
 const openReview=(id:string)=>setForm({kind:'review',id});
 const matched=!detail||detail.budgetId===snapshot.id;
 const modalTitle=form?.kind==='create'?'Create a group':form?.kind==='join'?'Join '+form.group.name:form?.kind==='member'?'Add a group member':form?.kind==='purchase'?'Add a group bill':form?.kind==='bill-review'?'Review group bill':form?.kind==='series'?'Recurring group bill':form?.kind==='change'?changeNames[form.draft.kind]:'Review shared change';
 function inviteMember(id:string){request.perform<{invitation:GroupInvitation}>('/expense-group-members/'+id+'/invite',{},value=>setInvite(value.invitation));}
 const reviewList=(values:SharedChange[])=>values.length>0&&<section className="group-reviews-list"><h3>Shared changes</h3>{values.map(change=><button key={change.id} disabled={!!request.pending} onClick={()=>openReview(change.id)}><span>{change.state==='applied'?<CheckCircle2 aria-hidden="true"/>:<Clock3 aria-hidden="true"/>}</span><span><strong>{changeNames[change.kind]}</strong><small>{change.merchant} · {change.state==='pending'?'Review needed':change.state==='applied'?'Applied':'Cancelled'}</small></span><ChevronRight aria-hidden="true"/></button>)}</section>;
 return <div className="expense-groups">
  {notice&&<div className="group-notice" role="status"><CheckCircle2 aria-hidden="true"/><span>{notice}</span><button className="icon-button" aria-label="Dismiss group confirmation" onClick={()=>setNotice('')}><X aria-hidden="true"/></button></div>}
  {error&&<div className="group-recovery" role="alert"><p>{error}</p><button className="button secondary" onClick={()=>void load(true)}>Try again</button></div>}
  {!form&&request.recovery}
  {invite&&<section className="group-invitation"><h3>Invite {invite.name}</h3><p>Join me in {invite.groupName} on SpentOn to review our shared bills and repayments.</p><p className="group-invite-link">{invite.url}</p><div className="button-row"><a className="button primary" href={'sms:?body='+encodeURIComponent(`Join me in ${invite.groupName} on SpentOn: ${invite.url}`)}>Open Messages</a><button className="button secondary" onClick={()=>void navigator.clipboard.writeText(invite.url).then(()=>setNotice('Invitation link copied.')).catch(()=>request.setError('Select and copy the link above.'))}>Copy invitation</button><button className="button ghost" onClick={()=>setInvite(null)}>Done</button></div><p className="group-note">Send this private link to the intended person. It expires in seven days.</p></section>}
  {!selected?<>
   <div className="groups-heading"><p>Keep a household, trip or event together.</p><button className="button primary" disabled={!groups||!!request.pending} onClick={()=>setForm({kind:'create'})}><Plus aria-hidden="true"/>New group</button></div>
   {!groups?(!error&&<LoadingState layout="list" label="Loading your groups"/>):!groups.length?<div className="group-empty"><Users aria-hidden="true"/><h2>Your first shared plan</h2><p>Create a group, add the people sharing costs, and record each bill once.</p><button className="button secondary" onClick={()=>setForm({kind:'create'})}>Create a group</button></div>:<div className="groups-list">{groups.map(group=>{
    const Icon=group.kind==='trip'?Plane:group.kind==='household'?House:Users;
    return <button className="group-list-row" key={group.id} disabled={!!request.pending} onClick={()=>group.membership==='invited'?setForm({kind:'join',group}):onSelect(group.id)}><span className="group-kind"><Icon aria-hidden="true"/></span><span><strong>{group.name}</strong><small>{group.memberCount} people · {group.currency}{group.membership==='invited'?' · Invitation':group.state==='archived'?' · Archived':''}</small></span><ChevronRight aria-hidden="true"/></button>;
   })}</div>}
   {reviewList(reviews)}
  </>:detail?<>
   <button className="text-button" disabled={!!request.pending} onClick={()=>onSelect('')}><ArrowLeft aria-hidden="true" size={16}/>All groups</button>
   <div className="groups-heading"><div><h2>{detail.name}</h2><p>{detail.members.length} people · {detail.currency} · {detail.kind==='trip'?'Trip':detail.kind==='household'?'Household':'Event'}</p></div><button className="button primary" disabled={!matched||detail.state!=='active'||!!request.pending} onClick={()=>setForm({kind:'purchase'})}><Plus aria-hidden="true"/>Add bill</button></div>
   {!matched&&<p className="group-recovery">Open the budget you joined this group with to add bills or approve changes.</p>}
   <div className="group-total"><span>Group spending</span><strong>{money(detail.total,detail.currency)}</strong><small>Recorded bills minus merchant refunds.</small></div>
   <section className="group-people"><div className="people-section-heading"><h3>People in this group</h3>{detail.canManage&&detail.state==='active'&&<button className="text-button" disabled={!!request.pending} onClick={()=>setForm({kind:'member'})}>Add person</button>}</div><div className="group-roster">{detail.members.map(person=><div key={person.id}><PersonAvatar name={person.name} identity={person.id}/><span><strong>{person.name}{person.isYou?' (you)':''}</strong><small>{person.state==='active'?'Joined':person.state==='removed'?'Account removed':'Awaiting invitation acceptance'}</small></span>{person.state==='invited'&&detail.state==='active'&&<button className="text-button" disabled={!!request.pending} onClick={()=>inviteMember(person.id)}>Invite</button>}</div>)}</div></section>
   <div className="group-columns">
    <section><div className="people-section-heading"><h3>Shares and payments</h3><Receipt aria-hidden="true"/></div><div className="group-balance-table">{detail.balances.map(balance=><div key={balance.memberId}><strong>{balance.name}</strong><dl><div><dt>Paid for the group</dt><dd>{money(balance.paid,detail.currency)}</dd></div><div><dt>Personal share</dt><dd>{money(balance.share,detail.currency)}</dd></div><div><dt>{balance.owed>=balance.owing?'Net owed to them':'Net they owe'}</dt><dd>{money(Math.abs(balance.owed-balance.owing),detail.currency)}</dd></div></dl></div>)}</div><p className="group-note">Shares include recorded requests. Each person reviews their own budget before accepting. Use the person-by-person balances for repayments.</p></section>
    <section><h3>You and each person</h3>{detail.settlements.filter(p=>p.owesYou||p.youOwe).map(pair=><div className="group-pair" key={pair.memberId}><strong>{pair.name}</strong><dl><div><dt>They owe you</dt><dd>{money(pair.owesYou,detail.currency)}</dd></div><div><dt>You owe them</dt><dd>{money(pair.youOwe,detail.currency)}</dd></div></dl><p>{pair.net===0?'Your balances match.':pair.net>0?`After offsets, they would pay you ${money(pair.net,detail.currency)}.`:`After offsets, you would pay ${money(-pair.net,detail.currency)}.`}</p>{pair.canOffset&&<button className="button secondary" disabled={!matched||!!request.pending} onClick={()=>setForm({kind:'change',draft:{kind:'offset',group:detail,pair}})}>Review {money(pair.offsettable,detail.currency)} offset</button>}<details><summary>See the original bills</summary>{pair.lines.filter(l=>l.amount>0).map(line=><button className="group-pair-bill" key={line.shareId} onClick={()=>onExpense(detail.id,line.expenseId)}><span>{line.merchant}<small>{line.direction==='incoming'?'They owe you':'You owe them'}</small></span><strong>{money(line.amount,detail.currency)}</strong><ChevronRight aria-hidden="true"/></button>)}</details></div>)}{!detail.settlements.some(p=>p.owesYou||p.youOwe)&&<p className="group-note">You have no outstanding balances in this group.</p>}</section>
   </div>
   {detail.billVersion===1&&<GroupBillSections group={detail} request={request} onBill={id=>setForm({kind:'bill-review',id})} onSchedule={series=>{if(matched)setForm({kind:'series',series});else request.setError('Open the budget you joined this group with.');}} onChanged={()=>void load()}/>}
   {reviewList(detail.changes)}
   <section className="group-bills"><h3>Group bills</h3>{!detail.bills.length?<p className="group-note">Add the first bill to see everyone’s share.</p>:detail.bills.filter(b=>!(detail.combinedBills??[]).some(p=>p.payers.some(a=>a.expenseId===b.id))).map(bill=><article key={bill.id}><div><strong>{bill.merchant}</strong><small>{bill.kind==='refund'?'Refund to return':'Paid by '+(detail.members.find(m=>m.id===bill.payerId)?.name??'Former member')} · {bill.date}</small></div><div className="group-bill-amount"><strong>{money(bill.total-bill.refunded,detail.currency)}</strong>{bill.refunded>0&&<small>{money(bill.refunded,detail.currency)} refunded</small>}</div>{!bill.archived&&(bill.payerId===detail.memberId||bill.shares.some(s=>s.memberId===detail.memberId))?<button className="button secondary" onClick={()=>onExpense(detail.id,bill.id)}>Review bill</button>:<span className="group-note">{bill.archived?'Retained history':'No share assigned to you'}</span>}<details className="group-bill-shares"><summary>See shares</summary><dl><div><dt>{detail.members.find(m=>m.id===bill.payerId)?.name??'Former member'}</dt><dd>{money(bill.kind==='purchase'?bill.total-bill.refunded-bill.shares.filter(s=>s.state!=='cancelled').reduce((n,s)=>n+s.amount-s.refunded,0):0,detail.currency)}</dd></div>{bill.shares.filter(s=>s.state!=='cancelled').map(s=><div key={s.id}><dt>{detail.members.find(m=>m.id===s.memberId)?.name??'Former member'}{s.state==='invited'?' (awaiting acceptance)':''}</dt><dd>{money(s.amount-s.refunded,detail.currency)}</dd></div>)}</dl></details></article>)}</section>
   {detail.canManage&&detail.state==='active'&&<button className="text-button" disabled={!!request.pending||detail.balances.some(b=>b.owed||b.owing||b.pending)||detail.changes.some(c=>c.state==='pending')} onClick={async()=>{if(await confirm({title:'Archive '+detail.name+'?',description:'Its bills and history will remain available. You can no longer add bills to this group.',confirmLabel:'Archive group',destructive:true}))request.perform<{group:GroupDetail}>('/expense-groups/'+detail.id,{expectedGroupRevision:detail.revision,actionType:'archive'},result=>{setDetail(result.group);setNotice('Group archived.');});}}>Archive settled group</button>}
  </>:!error&&<LoadingState layout="list" label="Loading this group"/>}
  {form&&<Modal title={modalTitle} onClose={close} wide className="group-dialog"><div className="form-body">{request.recovery}
   {form.kind==='create'&&<CreateGroup snapshot={snapshot} request={request} onCreated={group=>{setForm(null);onSelect(group.id);setNotice('Group created. Invite your people when ready.');}} onCancel={close}/>}
   {form.kind==='join'&&<div className="group-form"><p>Members can see the group’s bills, shares and repayment records. Your personal budget and account balances stay private.</p><p>Use <strong>{snapshot.budget.name}</strong> for your expenses in this group. Joining does not accept or pay any bill.</p>{snapshot.budget.currency!==form.group.currency?<p>Open a {form.group.currency} budget to join.</p>:<button className="button primary" disabled={request.busy||!!request.pending} onClick={()=>request.perform<{group:GroupDetail}>('/group-invitations/join',{memberId:form.group.invitationId,budgetId:snapshot.id,expectedRevision:snapshot.revision,confirmJoin:true},value=>{setForm(null);onSelect(value.group.id);setNotice('You joined the group.');})}>Join group</button>}<button className="button ghost" disabled={!request.canClose()} onClick={close}>Cancel</button></div>}
   {form.kind==='purchase'&&detail?.billVersion!==1&&detail&&<GroupPurchase group={detail} snapshot={snapshot} request={request} onDone={()=>{setForm(null);setNotice('Bill and shares saved.');void load();}} onCancel={close}/>}
   {((form.kind==='purchase'&&detail?.billVersion===1)||form.kind==='series')&&detail&&<GroupBillComposer group={detail} snapshot={snapshot} request={request} series={form.kind==='series'?form.series:undefined} recurring={form.kind==='series'} onBill={bill=>setForm({kind:'bill-review',id:bill.id})} onDone={()=>{setForm(null);setNotice(form.kind==='series'?'Recurring bill saved.':'Bill saved.');void load();}} onCancel={close}/>}
   {form.kind==='bill-review'&&<GroupBillReview id={form.id} snapshot={snapshot} request={request} onDone={close} onExpense={id=>{if(request.canClose()){close();onExpense(selected,id);}}}/>}
   {form.kind==='member'&&detail&&<AddMember group={detail} request={request} onDone={group=>{setDetail(group);setForm(null);}} onCancel={close}/>}
   {form.kind==='change'&&<SharedChangeComposer draft={form.draft} snapshot={snapshot} request={request} onCreated={change=>setForm({kind:'review',id:change.id})} onCancel={close}/>}
   {form.kind==='review'&&<SharedChangeReview id={form.id} snapshot={snapshot} request={request} onDone={close} onReverse={change=>setForm({kind:'change',draft:{kind:'reverse_offset',change}})}/>}
  </div></Modal>}
 </div>;
}

function CreateGroup({snapshot,request,onCreated,onCancel}:{snapshot:CloudBudget;request:Request;onCreated:(value:GroupDetail)=>void;onCancel:()=>void}){
 const [name,setName]=useState(''),[kind,setKind]=useState('trip'),[yourName,setYourName]=useState(''),[people,setPeople]=useState([{name:'',email:''}]);
 const savedDraft=useSharingFormDraft(request.scope,'create-group',snapshot.revision,{name,kind,yourName,people:JSON.stringify(people)},saved=>{setName(saved.name??'');setKind(['trip','household','event'].includes(saved.kind)?saved.kind:'trip');setYourName(saved.yourName??'');try{const rows=JSON.parse(saved.people??'[]');if(Array.isArray(rows)&&rows.length<=19&&rows.every(p=>typeof p.name==='string'&&typeof p.email==='string'))setPeople(rows);}catch{/* Invalid local data is not restored. */}},!!name||!!yourName||kind!=='trip'||people.some(p=>!!p.name||!!p.email));
 const cancel=()=>{savedDraft.clear();onCancel();};
 return <form className="group-form" onSubmit={event=>{event.preventDefault();request.perform<{group:GroupDetail}>('/expense-groups',{name,kind,yourName,budgetId:snapshot.id,expectedRevision:snapshot.revision,members:people.filter(p=>p.name||p.email)},value=>{savedDraft.clear();onCreated(value.group);});}}>{savedDraft.notice}<fieldset disabled={request.busy||!!request.pending||savedDraft.needsReview}>
  <Field label="Group name"><input autoFocus required maxLength={80} value={name} onChange={e=>setName(e.target.value)} placeholder="Our September trip"/></Field>
  <Field label="Group type"><Select value={kind} onChange={e=>setKind(e.target.value)}><option value="trip">Trip</option><option value="household">Household</option><option value="event">Event</option></Select></Field>
  <Field label="Your name in this group"><input required maxLength={100} value={yourName} onChange={e=>setYourName(e.target.value)}/></Field>
  <p className="group-note">Your group uses {snapshot.budget.currency}. Your personal expenses will belong to {snapshot.budget.name}.</p>
  {people.map((person,index)=><div className="group-member-fields" key={index}><Field label={'Person '+(index+1)+' name'}><input required={!!person.email} maxLength={100} value={person.name} onChange={e=>setPeople(rows=>rows.map((p,i)=>i===index?{...p,name:e.target.value}:p))}/></Field><Field label="Email (optional)"><input type="email" autoComplete="off" maxLength={254} value={person.email} onChange={e=>setPeople(rows=>rows.map((p,i)=>i===index?{...p,email:e.target.value}:p))}/></Field>{people.length>1&&<button className="text-button" type="button" onClick={()=>setPeople(rows=>rows.filter((_,i)=>i!==index))}>Remove person</button>}</div>)}
  {people.length<19&&<button type="button" className="button secondary" onClick={()=>setPeople(rows=>[...rows,{name:'',email:''}])}><Plus aria-hidden="true"/>Add person</button>}
  <p className="group-note">Members can review shared bills and balances. Their personal budgets stay private. Invitations are sent by you.</p>
  <div className="button-row"><button className="button primary" type="submit">Create group</button><button className="button ghost" type="button" onClick={cancel}>Cancel</button></div>
 </fieldset></form>;
}

function AddMember({group,request,onDone,onCancel}:{group:GroupDetail;request:Request;onDone:(group:GroupDetail)=>void;onCancel:()=>void}){
 const [name,setName]=useState(''),[email,setEmail]=useState('');
 const savedDraft=useSharingFormDraft(request.scope,'group-member-'+group.id,0,{name,email},saved=>{setName(saved.name??'');setEmail(saved.email??'');},!!name||!!email);
 const cancel=()=>{savedDraft.clear();onCancel();};
 return <form className="group-form" onSubmit={e=>{e.preventDefault();request.perform<{group:GroupDetail}>('/expense-groups/'+group.id,{actionType:'add-member',expectedGroupRevision:group.revision,member:{name,email}},value=>{savedDraft.clear();onDone(value.group);});}}>{savedDraft.notice}<fieldset disabled={request.busy||!!request.pending||savedDraft.needsReview}><Field label="Name"><input required maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Email (optional)"><input type="email" maxLength={254} value={email} onChange={e=>setEmail(e.target.value)}/></Field><p className="group-note">This person can review the group’s existing bills after joining. Existing shares stay unchanged.</p><div className="button-row"><button className="button primary" type="submit">Add person</button><button type="button" className="button ghost" onClick={cancel}>Cancel</button></div></fieldset></form>;
}

function GroupPurchase({group,snapshot,request,onDone,onCancel}:{group:GroupDetail;snapshot:CloudBudget;request:Request;onDone:()=>void;onCancel:()=>void}){
 const b=snapshot.budget,[entryId]=useState(crypto.randomUUID()),[amount,setAmount]=useState(''),[merchant,setMerchant]=useState(''),[date,setDate]=useState(today()),[account,setAccount]=useState(b.accounts.find(a=>a.type==='checking')?.id??b.accounts[0]?.id??''),[category,setCategory]=useState(b.categories.find(c=>c.icon===(group.kind==='trip'?'plane':group.kind==='household'?'basket':'coffee'))?.id??b.categories[0]?.id??''),[equal,setEqual]=useState(true);
 const [people,setPeople]=useState(group.members.filter(m=>!m.isYou&&m.state!=='removed').map(m=>({...m,included:true,amount:''})));
 const savedDraft=useSharingFormDraft(request.scope,'group-purchase-'+group.id,snapshot.revision,{amount,merchant,date,account,category,equal:String(equal),context:JSON.stringify(group.members.filter(m=>!m.isYou&&m.state!=='removed').map(m=>m.id).sort()),people:JSON.stringify(people.map(p=>({id:p.id,included:p.included,amount:p.amount})))},saved=>{setAmount(saved.amount??'');setMerchant(saved.merchant??'');setDate(saved.date??today());setAccount(b.accounts.some(a=>a.id===saved.account)?saved.account:'');setCategory(b.categories.some(c=>c.id===saved.category)?saved.category:'');setEqual(saved.equal!=='false');try{const rows=JSON.parse(saved.people??'[]');if(Array.isArray(rows))setPeople(current=>current.map(p=>{const old=rows.find(r=>r.id===p.id);return {...p,included:old?.included===true,amount:typeof old?.amount==='string'?old.amount:''};}));}catch{/* Keep the current group roster. */}},!!amount||!!merchant||!equal);
 const cancel=()=>{savedDraft.clear();onCancel();};
 const selected=people.filter(p=>p.included),fmt=(value:number)=>money(value,group.currency);
 let total=0,parts:number[]=[],preview:ReturnType<typeof previewSharedBudget>|null=null;
 try{total=cents(amount);parts=selected.map(p=>equal?Math.floor(total/(selected.length+1)):cents(p.amount));if(total>0&&parts.every(a=>a>0)&&parts.reduce((n,a)=>n+a,0)<=total){const draft={id:entryId,kind:'expense' as const,amount:total,date,accountId:account,categoryId:category,payee:merchant,note:'',cleared:false};preview=previewSharedBudget({...b,entries:[...b.entries,draft]},{kind:'split',entryId,amount:String(parts.reduce((n,a)=>n+a,0))});}}catch{/* Incomplete amounts remain editable. */}
 function submit(){if(!preview||!selected.length){request.setError('Enter a purchase and valid shares for at least one other member.');return;}request.perform('/shared-expenses',{budgetId:snapshot.id,expectedRevision:snapshot.revision,groupId:group.id,expectedGroupRevision:group.revision,entryId,purchase:{entry:{id:entryId,kind:'expense',amount:total,date,accountId:account,categoryId:category,payee:merchant,note:'',cleared:false}},shares:selected.map((p,i)=>({memberId:p.id,name:p.name,amount:parts[i]}))},()=>{savedDraft.clear();onDone();});}
 return <form className="group-form" onSubmit={e=>{e.preventDefault();submit();}}>{savedDraft.notice}<fieldset disabled={request.busy||!!request.pending||savedDraft.needsReview}>
  <Field label="Bill amount"><input autoFocus required inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/></Field>
  <Field label="What was it for?"><input required maxLength={160} value={merchant} onChange={e=>setMerchant(e.target.value)} placeholder="Train tickets"/></Field>
  <div className="field-row"><Field label="Paid from"><Select required value={account} onChange={e=>setAccount(e.target.value)}>{b.accounts.filter(a=>a.type!=='investment').map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</Select></Field><Field label="Your category"><Select required value={category} onChange={e=>setCategory(e.target.value)}>{b.categories.map(c=><option key={c.id} value={c.id}>{c.group} · {c.name}</option>)}</Select></Field></div>
  <Field label="Purchase date"><DatePicker required value={date} onChange={setDate} max={today()}/></Field>
  <label className="shared-check"><input type="checkbox" checked={equal} onChange={e=>setEqual(e.target.checked)}/>Split equally, including me</label>
  <div className="group-purchase-people">{people.map(person=><div key={person.id}><label className="shared-check"><input type="checkbox" checked={person.included} onChange={e=>setPeople(values=>values.map(p=>p.id===person.id?{...p,included:e.target.checked}:p))}/><PersonAvatar name={person.name} identity={person.id}/>{person.name}</label>{person.included&&(equal?<strong>{total>0?fmt(Math.floor(total/(selected.length+1))):'Not set'}</strong>:<input aria-label={'Share for '+person.name} inputMode="decimal" required value={person.amount} onChange={e=>setPeople(values=>values.map(p=>p.id===person.id?{...p,amount:e.target.value}:p))}/>)}</div>)}</div>
  {preview&&<div className="group-own-impact" aria-live="polite"><dl><div><dt>Your spending</dt><dd><strong>{fmt(preview.personalSpending)}</strong></dd></div><div><dt>Friends owe you</dt><dd><strong>{fmt(parts.reduce((n,a)=>n+a,0))}</strong></dd></div><div><dt>Left in your category</dt><dd><strong>{fmt(preview.categoryLeft)}</strong></dd></div><div><dt>Available to plan</dt><dd><strong>{fmt(preview.ready)}</strong></dd></div></dl><p className="group-note">The full payment is recorded in your account. Each person reviews their share before it enters their budget. Any rounding remainder stays in your share.</p></div>}
  <div className="button-row"><button type="submit" className="button primary" disabled={!preview||!selected.length}>Save purchase and split</button><button type="button" className="button ghost" onClick={cancel}>Cancel</button></div>
 </fieldset></form>;
}
