import {useState} from 'react';
import {ArrowDownLeft,ArrowUpRight,ArrowRight,ChevronRight,ShieldCheck,ChartNoAxesCombined,Target,Wallet} from 'lucide-react';
import {money,today,spendingAmount} from './engine';
import type {Budget,Category,Totals} from './engine';
import {reviewMoney,spendingComparison} from './insights';
import type {InsightAction} from './insights';
import {CategoryIcon,Progress} from './ui';
import './insights-design.css';

export default function Insights({b,t,month,totalLeft,openCategory,act}:{b:Budget;t:Totals;month:string;totalLeft:number;openCategory:(c:Category)=>void;act:(a:InsightAction)=>void}){
 const [allCategories,setAllCategories]=useState(false),[allNotes,setAllNotes]=useState(false);
 const fmt=(n:number)=>money(n,b.currency),items=reviewMoney(b,t,month),lead=items[0],comparison=spendingComparison(b,month);
 const categories=b.categories.filter(c=>t.categories[c.id].spent!==0).sort((a,z)=>t.categories[z.id].spent-t.categories[a.id].spent);
 const positive=categories.reduce((sum,c)=>sum+Math.max(0,t.categories[c.id].spent),0),largest=Math.max(1,...categories.map(c=>Math.abs(t.categories[c.id].spent)));
 const goals=b.categories.filter(c=>c.targetType==='balance'&&c.target>0),purchases=t.transactions.filter(e=>e.kind==='expense'||e.kind==='shared_charge'),refunds=t.transactions.filter(e=>spendingAmount(e)<0);
 const monthName=new Date(month+'-01T12:00:00').toLocaleDateString('en-US',{month:'long',year:'numeric'});
 const endDay=new Date(Number(month.slice(0,4)),Number(month.slice(5,7)),0).getDate(),lastRecorded=Math.max(1,...[...purchases,...refunds].map(e=>Number(e.date.slice(8))));
 const shownDays=month===today().slice(0,7)?Math.max(Number(today().slice(8)),lastRecorded):endDay;
 let running=0;const values=Array.from({length:shownDays},(_,i)=>{running+=t.transactions.filter(e=>spendingAmount(e)!==0&&Number(e.date.slice(8))===i+1).reduce((sum,e)=>sum+spendingAmount(e),0);return running;});
 const min=Math.min(0,...values),max=Math.max(1,...values),range=max-min;
 const coords=values.map((value,i)=>[75+i/Math.max(1,shownDays-1)*535,165-(value-min)/range*135]),path=coords.map(([x,y],i)=>`${i?'L':'M'}${x},${y}`).join(' ');
 return <section className="insights-redesign" aria-label="Your money review">
  <div className="insight-summary"><div><span><ArrowUpRight size={15}/>Net spending</span><strong>{fmt(t.spent)}</strong><small>Your purchases and accepted shares, minus refunds</small></div><div><span><ArrowDownLeft size={15}/>Income recorded</span><strong>{fmt(t.income)}</strong><small>Excludes opening balances</small></div><div><span><Wallet size={15}/>In your categories</span><strong>{fmt(totalLeft)}</strong><small>Includes carried-over money</small></div><div><span><Target size={15}/>Available to plan</span><strong>{fmt(t.ready)}</strong><small>{t.ready<0?'Review your cash shortfall':'Not yet set aside'}</small></div></div>
  <div className="insights-workspace"><div className="insights-main-column">
   <section className="insights-panel spending-breakdown"><header><div><span className="insights-kicker">01 / YOUR SPENDING</span><h2>Where your money went</h2></div><span className="insights-period">{monthName}</span></header>
    {categories.length?<><div className="spending-caption"><strong>{categories.length} categor{categories.length===1?'y':'ies'}</strong><span>{purchases.length} purchase{purchases.length===1?'':'s'} recorded{refunds.length?` · ${refunds.length} refund${refunds.length===1?'':'s'}`:''}</span></div><div className="insights-category-bars">{(allCategories?categories:categories.slice(0,5)).map(c=>{const spent=t.categories[c.id].spent;return <button key={c.id} onClick={()=>openCategory(c)}><CategoryIcon category={c}/><div className="insights-bar-copy"><span><strong>{c.name}</strong><b>{fmt(spent)}</b></span><div className="insights-bar-track"><i className={spent<0?'refund':''} style={{width:`${100*Math.abs(spent)/largest}%`}}/></div></div><small>{spent<0?'Refunds':`${Math.round(100*spent/positive)}%`}</small><ChevronRight size={14}/></button>;})}</div>{categories.length>5&&<button className="text-button insights-show" onClick={()=>setAllCategories(!allCategories)}>{allCategories?'Show fewer categories':`View all ${categories.length} categories`}<ChevronRight size={14}/></button>}<p className="insights-fineprint">Shares use positive net spending. Refunds remain included in your total.</p></>:<div className="insights-empty-spending"><span className="insights-empty-icon"><ChartNoAxesCombined size={27}/></span><h3>No spending recorded</h3><p>Record purchases to compare spending by category.</p><button className="button secondary" onClick={()=>act({kind:'record'})}>Add a transaction<ArrowRight size={15}/></button></div>}
    <section className="review-comparison"><div><span className="insights-kicker">MONTH OVER MONTH</span><h3>{comparison.available?comparison.delta===0?'Recorded spending is unchanged':`${fmt(Math.abs(comparison.delta))} ${comparison.delta>0?'more':'less'} recorded spending`:'A comparison needs two months of purchases'}</h3><p>{comparison.available?comparison.period:'Your comparison will appear when this month and the previous month both contain purchases.'}</p></div>{comparison.available&&<div className="review-drivers">{comparison.changes.slice(0,3).map(x=><button key={x.category.id} onClick={()=>openCategory(x.category)}><span>{x.category.name}<small>{fmt(x.previous)} → {fmt(x.current)}</small></span><strong>{x.delta>0?'+':'−'}{fmt(Math.abs(x.delta))}</strong></button>)}</div>}<small className="insights-fineprint">{comparison.partial?'Matching calendar days. ':''}Recorded purchases less refunds; transfers and card payments excluded. Missing entries can change the picture.</small></section>
   </section>
   <section className="insights-panel insights-timeline"><header><div><span className="insights-kicker">02 / THROUGH THE MONTH</span><h2>Spending through the month</h2></div><span className="insights-period">Cumulative</span></header>{purchases.length||refunds.length?<><svg viewBox="0 0 640 205" role="img" aria-label={`Cumulative spending in ${monthName}, ending at ${fmt(t.spent)}`}><defs><linearGradient id="insights-area" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#adc1a2" stopOpacity=".4"/><stop offset="100%" stopColor="#adc1a2" stopOpacity="0"/></linearGradient></defs>{[0,.5,1].map(f=>{const y=165-f*135;return <g key={f}><line x1="75" y1={y} x2="610" y2={y} stroke="#e5e8df" strokeDasharray="3 5"/><text x="65" y={y+4} textAnchor="end">{fmt(Math.round(min+f*range))}</text></g>;})}<path d={`${path} L${coords.at(-1)![0]},165 L75,165 Z`} fill="url(#insights-area)"/><path d={path} fill="none" stroke="#416854" strokeWidth="3" strokeLinejoin="round"/><circle cx={coords.at(-1)![0]} cy={coords.at(-1)![1]} r="4" fill="#416854"/><text x="75" y="195">Day 1</text><text x="610" y="195" textAnchor="end">Day {shownDays}</text></svg><p className="insights-fineprint">Recorded net spending through day {shownDays}. This is a running total, not a forecast.</p></>:<div className="insights-timeline-empty"><ChartNoAxesCombined size={21}/><p>Record a purchase or refund to see the chart.</p></div>}</section>
  </div><aside className="insights-side-column" aria-label="Your next steps">
   <section className={'money-review-lead '+lead.tone}><span className="insights-kicker">YOUR NEXT MOVE</span><span className="insights-lead-icon"><ArrowUpRight size={23}/></span><h2>{lead.title}</h2><p>{lead.detail}</p><button className="button" onClick={()=>act(lead.action)}>{lead.label}<ArrowRight size={16}/></button></section>
   {items.length>1&&<section className="insights-notes"><header><h2>More to review</h2><span>{items.length-1}</span></header>{(allNotes?items.slice(1):items.slice(1,3)).map(item=><article key={item.id}><i className={item.tone}/><div><h3>{item.title}</h3><p>{item.detail}</p><button className="text-button" onClick={()=>act(item.action)}>{item.label}<ArrowRight size={14}/></button></div></article>)}{items.length>3&&<button className="text-button insights-show" onClick={()=>setAllNotes(!allNotes)}>{allNotes?'Show fewer observations':`Show ${items.length-3} more observations`}</button>}</section>}
   <section className="insights-panel insights-goals"><header><div><span className="insights-kicker">03 / LOOKING AHEAD</span><h2>Your savings goals</h2></div><Target size={19}/></header>{goals.length?goals.map(c=>{const available=Math.max(0,t.categories[c.id].available),percent=Math.min(100,Math.round(100*available/c.target));return <button key={c.id} onClick={()=>openCategory(c)}><div><CategoryIcon category={c}/><strong>{c.name}</strong><span>{percent}%</span></div><Progress value={percent} label={c.name+' progress'}/><small>{fmt(available)} <span>of {fmt(c.target)}</span></small></button>;}):<div className="insights-goal-empty"><p>Set a savings goal for a category.</p>{b.categories[0]&&<button className="text-button" onClick={()=>openCategory(b.categories[0])}>Choose a savings goal<ArrowRight size={14}/></button>}</div>}</section>
  </aside></div>
  <footer className="insights-method"><span><ShieldCheck size={15}/>Private by design. Calculated from your budget.</span><details><summary>How these insights work</summary><p>Cash shortfalls appear before money available to plan and savings goals. Balances use recorded entries through the selected month’s end, including future-dated entries already posted. Scheduled transactions are excluded until recorded. Current-month comparisons use matching calendar days, limited to the shorter month; past months use full recorded months. Both periods need purchases for a comparison. No budget data is sent to an AI service, and viewing insights does not move money.</p></details></footer>
 </section>;
}
