import {useState} from 'react';
import {ArrowRight, ShieldCheck} from 'lucide-react';
import {money} from './engine';
import type {Budget,Category,Totals} from './engine';
import {reviewMoney,spendingComparison} from './insights';
import type {InsightAction} from './insights';
import './money-review.css';
export default function MoneyReview({b,t,month,act,openCategory}:{b:Budget;t:Totals;month:string;act:(a:InsightAction)=>void;openCategory:(c:Category)=>void}){
 const [expanded,setExpanded]=useState(false),items=reviewMoney(b,t,month),lead=items[0],comparison=spendingComparison(b,month),fmt=(n:number)=>money(n,b.currency);
 const secondary=items.slice(1),shown=expanded?secondary:secondary.slice(0,2);
 return <section className="money-review" aria-label="Your money review">
  <div className={'money-review-lead '+lead.tone}><div><span className="eyebrow">YOUR NEXT MOVE</span><h2>{lead.title}</h2><p>{lead.detail}</p><button className="button primary" onClick={()=>act(lead.action)}>{lead.label}<ArrowRight size={16}/></button></div><div className="review-context"><ShieldCheck size={20}/><strong>A review of your recorded money</strong><span>Calculated privately from your budget. Updated as your entries change.</span><small>{items.filter(x=>x.tone==='attention').length?`${items.filter(x=>x.tone==='attention').length} cash shortfall${items.filter(x=>x.tone==='attention').length===1?'':'s'} to review`:'Review your recorded balances.'}</small></div></div>
  {!!shown.length&&<div className="review-actions">{shown.map(item=><article key={item.id} className={item.tone}><span className="eyebrow">{item.tone==='attention'?'NEEDS ATTENTION':item.tone==='opportunity'?'LOOKING AHEAD':'YOUR DATA'}</span><h3>{item.title}</h3><p>{item.detail}</p><button className="text-button" onClick={()=>act(item.action)}>{item.label}<ArrowRight size={15}/></button></article>)}</div>}
  {secondary.length>2&&<button className="text-button review-more" onClick={()=>setExpanded(!expanded)}>{expanded?'Show fewer observations':`Show ${secondary.length-2} more observations`}</button>}
  <section className="review-comparison"><div><span className="eyebrow">WHAT CHANGED</span><h2>{comparison.available?comparison.delta===0?'Recorded spending is unchanged':`${fmt(Math.abs(comparison.delta))} ${comparison.delta>0?'more':'less'} recorded spending`:'A comparison needs two months of purchases'}</h2><p>{comparison.available?comparison.period:'Once both this month and the previous month have purchases, you’ll see the difference here. Missing entries can change the picture.'}</p>{comparison.available&&<small>{comparison.partial?'Matching calendar days only. ':''}Purchases less refunds; transfers and card payments excluded. This compares recorded entries, not a forecast.</small>}</div>{comparison.available&&<div className="review-drivers"><div className="review-period-totals"><span>This period<strong>{fmt(comparison.current)}</strong></span><span>Previous period<strong>{fmt(comparison.before)}</strong></span></div>{comparison.changes.slice(0,3).map(x=><button key={x.category.id} onClick={()=>openCategory(x.category)}><span>{x.category.name}<small>{fmt(x.previous)} → {fmt(x.current)}</small></span><strong>{x.delta>0?'+':'−'}{fmt(Math.abs(x.delta))}</strong></button>)}</div>}</section>
  <details className="review-method"><summary>How this review works</summary><p>Funding gaps come first, followed by unplanned cash and goal contributions. Monthly balances include recorded entries through the selected month’s end, including any future-dated entries already in the ledger. Scheduled transactions are excluded until recorded. Current-month spending comparisons use the same calendar days in both months (limited to the shorter month). No budget data is sent to an AI service, and no money moves until you choose an action and save.</p></details>
 </section>;
}
