import LoadingState from './LoadingState';
import {useEffect,useState} from 'react';
import {useOnboarding} from './onboarding-client';
import {OnboardingProblem} from './OnboardingJourney';
export default function OnboardingPreferences({userId}:{userId:string}){
 const controller=useOnboarding(userId),[enabled,setEnabled]=useState(false),[saved,setSaved]=useState(false);
 useEffect(()=>{if(controller.state)setEnabled(controller.state.analyticsConsent);},[controller.state?.analyticsConsent]);
 return <section className="onboarding-privacy"><h3>Help make getting started easier</h3><p>Your setup progress is saved so you can pick up where you left off. Sharing it for product improvement is a separate, optional choice.</p>{controller.state&&<><label className="learning-consent"><input type="checkbox" checked={enabled} disabled={controller.busy||controller.pending} onChange={e=>{setEnabled(e.target.checked);setSaved(false);}}/><span><strong>Share guide progress to help improve SpentOn</strong><small>We count the steps people finish, the help they open and any problems they meet. We do not include amounts, names, notes, anything you type, or screen recordings. The report shows group totals.</small></span></label><button className="button secondary" disabled={controller.busy||controller.pending} onClick={()=>void controller.command({operation:'consent',enabled}).then(ok=>{if(ok)setSaved(true);})}>{controller.busy?'Saving…':'Save setup privacy choice'}</button><p className="learning-private">Turning this off deletes your guide activity and removes you from the report. Pip still remembers where you stopped. Guide activity is deleted after 90 days.</p></>}{controller.loading&&<LoadingState layout="inline" label="Loading your setup preference"/>}{saved&&<p role="status" className="cloud-notice">{enabled?'Sharing is on. Thank you for helping us improve.':'Sharing is off. You still get the same help from Pip.'}</p>}<OnboardingProblem controller={controller}/></section>;
}
