import {useRef,useState} from 'react';
import {Star,ArrowRight} from 'lucide-react';
import {api} from './cloud';
import './onboarding-feedback.css';
export type FeedbackAnswers={rating:number;understood:string;comment:string;mutationId:string};
export function OnboardingFeedback({onContinue,preview=false,onSubmit,testMode=false}:{onContinue:()=>void;preview?:boolean;onSubmit?:(answers:FeedbackAnswers)=>Promise<void>;testMode?:boolean}){
 const [rating,setRating]=useState(0),[understood,setUnderstood]=useState(''),[comment,setComment]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const pending=useRef<{rating:number;understood:string;comment:string;mutationId:string}|null>(null),sending=useRef(false);
 async function submit(){if(sending.current)return;if(!rating||!understood){setError('Choose a rating and whether the guide helped.');return;}sending.current=true;setBusy(true);setError('');pending.current??={rating,understood,comment:comment.trim(),mutationId:crypto.randomUUID()};try{if(onSubmit)await onSubmit(pending.current);else if(!preview)await api('/onboarding/feedback',{method:'POST',body:pending.current});onContinue();}catch(e){setError((e instanceof Error?e.message:'Feedback could not be saved.')+' Your answers are kept. Retry or continue without sending.');}finally{sending.current=false;setBusy(false);}}
 return <section className="setup-feedback" aria-label="Onboarding feedback"><span className="feedback-eyebrow">ONE LAST THING · OPTIONAL</span><h2>How was getting started?</h2><fieldset disabled={busy||!!pending.current}><legend>Your rating</legend><div className="rating-stars">{[1,2,3,4,5].map(n=><label key={n}><input type="radio" name="setup-rating" value={n} checked={rating===n} onChange={()=>setRating(n)}/><Star size={32} fill={n<=rating?'currentColor':'none'}/><span className="rating-label">{n} {n===1?'star':'stars'}</span></label>)}</div><p className="rating-description">{['Choose 1 to 5 stars','Difficult','Could be better','Okay','Helpful','Really helpful'][rating]}</p><p id="understanding-question">Did Pip help you understand how to plan your money?</p><div className="understood-options" role="group" aria-labelledby="understanding-question">{[['yes','Yes'],['partly','A little'],['no','Not yet']].map(([value,label])=><label key={value}><input type="radio" name="setup-understood" value={value} checked={understood===value} onChange={()=>setUnderstood(value)}/><span>{label}</span></label>)}</div><label className="feedback-comment">What could we improve? <span>(optional)</span><textarea value={comment} onChange={e=>setComment(e.target.value)} maxLength={1000} rows={3} placeholder="Was anything confusing, or missing?" aria-describedby="feedback-comment-hint"/></label><small id="feedback-comment-hint">Please leave out bank details and other private information.</small></fieldset><p className="feedback-privacy">{testMode?'Your answers are saved with this test, separate from customer feedback.':preview?'Design preview. These answers are not sent.':'Your optional answers help the SpentOn team improve setup. Your rating, answer, and any written feedback will be shared with the SpentOn team.'}</p>{error&&<p role="alert">{error}</p>}<button className="feedback-submit" disabled={busy} onClick={()=>void submit()}>{busy?'Sending…':error?'Retry and open my budget':'Submit and Open Budget'}<ArrowRight size={16}/></button><button className="feedback-skip" disabled={busy} onClick={onContinue}>Skip and open my budget</button></section>;
}
