import { useState } from 'react';
import { ArrowLeft, ArrowRight } from 'lucide-react';
import { Modal } from './ui';

const steps=[
 {title:'Start with money you already have.',body:'Enter today’s bank balance. Plan spending and savings with it. Add your next paycheck when it arrives.',note:'A credit limit is borrowing capacity. It does not add money to your plan.',example:['Bank balance','2,000','Available to plan']},
 {title:'Enter card debt and statement separately.',body:'Enter the full amount currently owed when you add a card. Then copy the statement amount and due date from your issuer. The statement may cover only part of the total balance.',note:'Opening card debt belongs to earlier purchases. Adding it should not create spending in this month.',example:['Card owed / statement due','600 / 400','Both numbers can be correct']},
 {title:'Buy in September. Pay in October.',body:'A 100 grocery purchase on September 20 counts as September spending. If the category has money, 100 is set aside for repayment. The October card payment uses it.',note:'The cash is still in your bank until payment day, but it is already committed. The October payment is not another expense.',example:['September spent / October paid','100 / 100','One purchase, counted once']},
 {title:'Check cash set aside for repayment.',body:'Check cash set aside against total card debt, not just the statement. Use money in your budget to cover any difference. Future income only counts when received.',note:'Use reconciliation to find missing or incorrect records. Different spending and payment months are expected; they do not need a balance adjustment.',example:['Card debt / cash set aside','600 / 450','150 still needs cash']},
];
export default function OnboardingGuide({onClose,onStart,onLearn,learningLabel,initialStep=0}:{onClose:()=>void;onStart?:()=>void;onLearn?:()=>void;learningLabel?:string;initialStep?:number}){
 const [index,setIndex]=useState(initialStep),step=steps[index];
 return <Modal title="A little help from Pip" onClose={onClose}><div className="form-body pip-guide"><div className="pip-guide-heading"><img src="/brand/pip.svg" width="108" height="108" alt="Pip, your coin pouch friend"/><div><span className="cloud-eyebrow">STEP {index+1} OF {steps.length}</span><h3>{step.title}</h3></div></div><p>{step.body}</p><div className="pip-example"><span>{step.example[0]}</span><strong>{step.example[1]}</strong><small>{step.example[2]} · illustrative amounts in your budget currency</small></div><p className="pip-note">{step.note}</p><div className="pip-step-dots" aria-label="Guide progress">{steps.map((_,i)=><button key={i} aria-label={'Go to guide step '+(i+1)} aria-current={i===index?'step':undefined} onClick={()=>setIndex(i)}/>)}</div></div><div className="modal-footer">{onLearn&&<button className="button secondary" onClick={onLearn}>{learningLabel}</button>}{index>0&&<button className="button ghost" onClick={()=>setIndex(index-1)}><ArrowLeft size={15}/>Back</button>}{index<steps.length-1?<button className="button primary" onClick={()=>setIndex(index+1)}>Next<ArrowRight size={15}/></button>:<button className="button primary" onClick={onStart??onClose}>{onStart?'Create my first budget':'Got it'}<ArrowRight size={15}/></button>}</div></Modal>;
}
