import Select from './Select';
import {OnboardingFeedback} from './OnboardingFeedback';
import {useEffect,useState} from 'react';
import {ArrowRight,Pause,ShieldCheck} from 'lucide-react';
import {money} from './engine';
import type {Budget,Totals} from './engine';
import {nextLearningStep} from './onboarding-client';
import type {OnboardingController} from './onboarding-client';
import './onboarding.css';
import './pip-journey.css';

export function OnboardingProblem({controller}:{controller:OnboardingController}){return controller.error?<div className="learning-error" role="alert"><span>{controller.error}</span><button type="button" className="text-button" disabled={controller.busy} onClick={()=>void controller.retry()}>Retry guide update</button><small>You can still use your budget.</small></div>:null;}

function Sandbox({stage,setStage,currency='INR'}:{stage:number;setStage:(value:number)=>void;currency?:string}){
 const fmt=(value:number)=>money(value*100,currency);
 return <div className="pip-sandbox"><div className="pip-demo-label">TRY PRETEND MONEY · THIS DOES NOT CHANGE YOUR BUDGET</div><div className="pip-demo-money" aria-live="polite"><div><span>In the bank</span><strong>{fmt(stage===3?900:1000)}</strong><small>Account balance</small></div><div className={stage>=2?'has-jobs':''}><span>Available to plan</span><strong>{fmt(stage===0?1000:stage===1?300:0)}</strong><small>{stage>=2?'All your money is planned':'Not yet planned'}</small></div></div><div className="pip-demo-jobs"><div><span>Everyday needs</span><strong>{fmt(stage===0?0:stage===3?600:700)}</strong><i style={{width:(stage===0?0:stage===3?60:70)+'%'}}/></div><div><span>Extra for surprises</span><strong>{fmt(stage>=2?300:0)}</strong><i style={{width:(stage>=2?30:0)+'%'}}/></div></div><p role="status" className="pip-demo-explanation">{stage===0?'You have 1,000 today. Let’s set aside 700 for everyday needs.':stage===1?'You still have 1,000 in the bank. You have only chosen what 700 is for. Let’s keep the other 300 for surprises.':stage===2?'Available to plan is 0, but you still have 1,000 in the bank. You have planned it all, including savings.':'When you spend 100, your bank balance drops to 900. Everyday needs has 600 left. You still have 300 for surprises.'}</p><div className="pip-demo-actions">{stage<2?<button type="button" className="button secondary" onClick={()=>setStage(stage+1)}>{stage===0?'Set aside 700 for everyday needs':'Keep 300 for surprises'}<ArrowRight size={15}/></button>:stage===2?<button type="button" className="text-button" onClick={()=>setStage(3)}>What happens if I spend 100?<ArrowRight size={14}/></button>:<button type="button" className="text-button" onClick={()=>setStage(0)}>Try the example again</button>}</div></div>;
}

export function LearningWelcome({controller,onStart,onDismiss,existing=false}:{controller:OnboardingController;onStart:()=>void;onDismiss?:()=>void;existing?:boolean}){
 const [stage,setStage]=useState(0),[experience,setExperience]=useState<'beginner'|'familiar'>(controller.state?.experience??'beginner'),[consent,setConsent]=useState(controller.state?.analyticsConsent??false);
 async function begin(){if(controller.state?.status!=='active')return controller.command({operation:'start',experience,analyticsConsent:consent});return true;}
 function explore(value:number){setStage(value);void begin();}
 async function useMoney(){if(await begin()){if(controller.state?.analyticsConsent!==consent)await controller.command({operation:'consent',enabled:consent});if(stage>=2)await controller.command({operation:'aha'});}onStart();}
 return <section className="pip-welcome learning-welcome" aria-label="Learn with Pip"><div className="pip-introduction"><img src="/brand/pip-welcome-small.png" alt="Pip, your budgeting companion" width="100" height="100"/><div><span className="learning-eyebrow">A LITTLE HELP FROM PIP</span><h2>{existing?'Let’s plan your money.':'Hi, I’m Pip. Let’s plan your money.'}</h2><p>I’ll explain each number as you use the app. First, let’s try a small example.</p></div></div><Sandbox stage={stage} setStage={explore}/><details className="pip-welcome-options"><summary>Help and privacy settings</summary><label className="field"><span>How much help would you like?</span><Select value={experience} onChange={e=>setExperience(e.target.value as 'beginner'|'familiar')} disabled={controller.state?.status==='active'}><option value="beginner">I’m new. Explain as we go.</option><option value="familiar">I’ve budgeted before. Keep it short.</option></Select></label><label className="learning-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span><strong>Help improve this guide (optional)</strong><small>Share milestones and guide interactions for an aggregate report. No amounts, payees, notes, field contents or recordings. Off by default; change it in Account &amp; privacy.</small></span></label></details><OnboardingProblem controller={controller}/><div className="learning-welcome-actions"><button type="button" className="button primary" disabled={controller.busy} onClick={()=>void useMoney()}>{stage>=2?'I understand. Use my own money':'Use my own money'}<ArrowRight size={15}/></button><button type="button" className="text-button" disabled={controller.busy} onClick={()=>void controller.command({operation:'dismiss'}).then(ok=>{if(ok)onDismiss?.();})}>I’ll try it on my own</button></div><p className="learning-private"><ShieldCheck size={13}/>You get the same help whether sharing is on or off.</p></section>;
}

export function WorkspaceLearning({controller,onCreate,onOpen}:{controller:OnboardingController;onCreate:()=>void;onOpen:(id:string)=>void}){const state=controller.state;if(!state||state.cohort!=='new'||['dismissed','completed'].includes(state.status))return null;if(state.status==='offered'||state.status==='active'&&!state.budgetId)return <LearningWelcome controller={controller} onStart={onCreate}/>;return <section className="learning-resume"><div><h2>Pip saved your place.</h2><p>Continue whenever you are ready.</p><OnboardingProblem controller={controller}/></div><button className="button secondary" disabled={controller.busy} onClick={()=>void controller.command({operation:'resume'}).then(ok=>{if(ok)state.budgetId?onOpen(state.budgetId):onCreate();})}>Continue with Pip<ArrowRight size={15}/></button></section>;}

export type LearningAction='account'|'plan'|'income'|'purchase'|'insights'|'goal';
const explanations={
 'Nothing available to plan?':'If Available to plan is 0, you have planned all your money. This does not mean your bank is empty. Check the category’s Left amount before spending.',
 'Set aside, Spent, Left?':'Set aside is money added minus money moved out this month. Spent is purchases minus refunds. Left includes unused money from earlier months and subtracts card purchases still needing cash.',
 'Account or category?':'An account tells you where your money is. A category tells you what it is for. The same bank account can hold money for food, rent and savings. Changing your plan does not move money at your bank.',
 'How do cards work?':'When a card purchase is covered by your plan, that money is kept for the card bill. Paying the bill is not new spending. The bill due now may be less than the total you owe.',
 'Goals and next month?':'A goal suggests how much to set aside. You still choose the amount and save your plan. Money you do not use stays in its category for next month. Check any overspending first.',
 'Cleared or reconciled?':'Cleared means your bank has confirmed the payment. Reconcile means checking that SpentOn and your bank agree. First, look for anything missing or entered twice. Only adjust the balance when you know why it differs.',
 'What do Insights mean?':'Insights shows where your money went and what you can still afford. A new budget may need more history before it can compare months. Open a category to see its details.',
};
export function OnboardingCoach({controller,budget,totals,currentPage,budgetId,onAction,onWorkspace,saving,onComplete}:{controller:OnboardingController;budget:Budget;totals:Totals;currentPage:string;budgetId:string;onAction:(action:LearningAction)=>void;onWorkspace:()=>void;saving:boolean;onComplete:()=>void;confirmedRevision?:number}){
 const state=controller.state,[topic,setTopic]=useState<keyof typeof explanations|null>(null),[practice,setPractice]=useState(false),[demo,setDemo]=useState(0),[finished,setFinished]=useState(false);const next=state?nextLearningStep(state):'welcome';
 useEffect(()=>{if(state?.status==='active'&&next!=='finish')controller.event(next,'viewed');},[next,state?.status,state?.analyticsConsent]);
 if(!state)return null;if(state.status==='completed'&&finished)return <OnboardingFeedback onContinue={()=>{setFinished(false);onComplete();}}/>;if(state.status!=='active')return null;
 if(state.budgetId&&state.budgetId!==budgetId)return <section className="learning-resume"><p>I saved your place in your first budget.</p><button className="button secondary" onClick={onWorkspace}>Open workspace</button></section>;
 const fmt=(n:number)=>money(n,budget.currency),lessons={welcome:{title:'Choose what your money is for.',body:'Accounts show where your money is. Categories show what it is for. Start with money you have today.',label:'Show me my accounts',action:'account'},budget:{title:'Let’s start with an account you use.',body:'Enter the money in your account today. Do not include money you could borrow on a credit card.',label:'Add my starting account',action:'account'},plan:{title:totals.ready>0?`You have ${fmt(totals.ready)} available to plan.`:totals.ready<0?(totals.cash<0?'You have spent more than you have.':'Your category amounts and spending need more cash.'):'All your money is planned.',body:totals.ready>0?'Set money aside for spending and savings. It stays in your bank.':totals.ready<0?`Your cash shortfall is ${fmt(-totals.ready)}. Check your account balances and transactions before planning more.`:'All your money is already planned. If you have received money that is missing here, add it as income. Otherwise, keep using your plan.',label:totals.ready>0?'Plan my money':totals.ready<0?'Check my accounts':'Add received income',action:totals.ready>0?'plan':totals.ready<0?'account':'income'},purchase:{title:'Your plan is saved. Record a purchase.',body:'Enter a purchase, its account and category. The preview shows what will change. Skip this step if you have nothing to record.',label:'Record a purchase',action:'purchase'},insights:{title:'Your purchase is saved. Review your spending.',body:'Insights shows what you spent and what you have left. It can compare months once you have more history.',label:'Help me read Insights',action:'insights'}} as const;
 const lesson=next==='finish'?null:lessons[next],disabled=controller.busy||controller.pending||saving;
 const chips: (keyof typeof explanations)[]=currentPage==='insights'?['What do Insights mean?','Set aside, Spent, Left?','Goals and next month?']:currentPage==='accounts'?['Account or category?','How do cards work?','Cleared or reconciled?']:['Nothing available to plan?','Set aside, Spent, Left?','Account or category?','How do cards work?','Goals and next month?'];
 return <section className="pip-coach" id="learning-coach" aria-label="Pip’s guidance"><div className="pip-coach-main"><img src="/brand/pip-welcome-small.png" alt="Pip" width="78" height="78"/><div className="pip-coach-speech"><span className="learning-eyebrow">LET’S MAKE SENSE OF IT TOGETHER</span><h2>{lesson?.title??'You know the basics now.'}</h2><p>{lesson?(state.experience==='familiar'?lesson.body.split('. ')[0].replace(/\.$/,'')+'.':lesson.body):'Keep adding your spending. Change your plan when you need to. You can find me in Help & guidance.'}</p><div className="pip-coach-actions">{next==='finish'?<button className="button secondary" disabled={disabled} onClick={()=>void controller.command({operation:'finish'}).then(ok=>setFinished(ok))}>I can take it from here</button>:next==='insights'&&currentPage==='insights'?<button className="button secondary" disabled={disabled} onClick={()=>void controller.command({operation:'review'})}>I understand this overview</button>:<button className="button secondary" disabled={disabled} onClick={()=>{controller.event(next,'action');if(lesson)onAction(lesson.action);}}>{lesson?.label}<ArrowRight size={14}/></button>}{(next==='plan'||next==='purchase')&&<button className="text-button" disabled={disabled} onClick={()=>void controller.command({operation:'skip',step:next})}>I’ll do this later</button>}</div></div><button className="text-button pip-less-help" aria-label="Pause guide" disabled={controller.busy} onClick={()=>void controller.command({operation:'pause'})}><Pause size={12}/>Pause help</button></div><div className="pip-ask"><span>Ask Pip</span>{chips.map(key=><button type="button" key={key} aria-pressed={topic===key} onClick={()=>setTopic(topic===key?null:key)}>{key}</button>)}<button type="button" aria-expanded={practice} onClick={()=>setPractice(!practice)}>Try pretend money</button></div>{topic&&<p className="pip-answer" role="status">{explanations[topic]}</p>}{practice&&<Sandbox stage={demo} setStage={setDemo} currency={budget.currency}/>}<OnboardingProblem controller={controller}/>{saving&&<p className="small muted">Saving your budget. I’ll show what comes next when it is saved.</p>}</section>;
}

