import AmountInput from './AmountInput';
import type {FeedbackAnswers} from './OnboardingFeedback';
import {OnboardingFeedback} from './OnboardingFeedback';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,Check,Home,RotateCcw,ShoppingBasket,Sparkles,Volume2,VolumeX,Wallet,Plus} from 'lucide-react';
import pipArtwork from './brand/pip.svg?raw';
import {cents,money,blankBudget,validateBudget,allocate,id,today,calculate,thisMonth} from './engine';
import type {Budget,Category} from './engine';
import {starterCategories,defaultStarters} from './StarterCategories';
import {pipStarterNames} from './starter-categories';
import {pipAudioUrl,warmPipAudio} from './pip-audio';
import './pip.css';
import './pip-review.css';

const isAmountInput=(value:string)=>/^[0-9,]*(?:\.[0-9]{0,2})?$/.test(value);
const currencies=[['USD','US dollar'],['INR','Indian rupee'],['EUR','Euro'],['GBP','British pound'],['CAD','Canadian dollar'],['AUD','Australian dollar']] as const;
const suggestions=starterCategories(pipStarterNames);
const cues=['Your partner on SpentOn. One little step at a time.','Choose the currency you use.','Click Everyday needs to set aside 700.','Click Surprises to set aside the remaining 300.','Click See it in SpentOn to see your digital envelopes.','Click Plan your money to begin your own setup.','Click Everyday needs for this example purchase.','Click Set up my budget to make your own plan.','Name your budget, then click Continue.','Name one account, choose its type, then click Continue.','Enter today’s balance, then click Choose categories.','Keep the categories you need, then click Plan your money.','Give every unit a purpose, including savings. Then click Review my budget.','Check your account and category amounts, then confirm below.','Your next step is up to you. You can add transactions later.','Add transaction records spending against an account and a category.','A goal suggests how much to save. Plan your money sets it aside.'];
const headings=['Oh, hello! I’m Pip.','Which currency feels familiar?','','','Planned. Not spent.','Your envelopes, now digital.','','Check Left before you spend.','What shall we call your budget?','Where is your money today?','Start with what you have.','Choose what matters to you.','Give your money a purpose.','Does this look right?','A plan you can come back to.','Whenever you spend.','A little help looking ahead.'];
function Envelope({kind,value,active,filled,onClick,format}:{kind:'everyday'|'surprises';value:number;active:boolean;filled:boolean;onClick:()=>void;format:(n:number)=>string}){
 return <button type="button" className={'cash-envelope '+kind+(active?' envelope-active':'')+(filled?' envelope-filled':'')} disabled={!active} onClick={onClick} aria-label={(kind==='everyday'?'Everyday needs':'Surprises')+(active?' envelope':'')}>
  <div className="envelope-paper"><div className="envelope-flap"/><div className="envelope-fold"/><div className="envelope-label">{kind==='everyday'?<ShoppingBasket size={25}/>:<Sparkles size={25}/>}<span>{kind==='everyday'?'Everyday needs':'Surprises'}</span><strong>{value?format(value):'Your envelope'}</strong></div>{filled&&<span className="envelope-seal"><Check size={16}/></span>}</div>
  {active&&<span className="envelope-tap">Set aside {format(kind==='everyday'?70000:30000)} <ArrowRight size={15}/></span>}
 </button>;
}
export default function PipSetup({preview=true,onSave,onComplete,onClose,onImport,testMode=false,onFeedback}:{preview?:boolean;onSave?:(budget:Budget)=>Promise<void>;onComplete?:()=>void;onClose?:()=>void;onImport?:()=>void;testMode?:boolean;onFeedback?:(answers:FeedbackAnswers)=>Promise<void>}){
 const [step,setStep]=useState(0),[started,setStarted]=useState(false),[muted,setMuted]=useState(false),[speaking,setSpeaking]=useState(false),[blocked,setBlocked]=useState(false),[audioError,setAudioError]=useState(false);
 const [currency,setCurrency]=useState<Budget['currency']>('INR'),[budgetName,setBudgetName]=useState(''),[account,setAccount]=useState(''),[accountType,setAccountType]=useState<'checking'|'savings'>('checking'),[balance,setBalance]=useState(''),[selected,setSelected]=useState(defaultStarters),[custom,setCustom]=useState<Category[]>([]),[amounts,setAmounts]=useState<Record<string,string>>({}),[error,setError]=useState(''),[wrong,setWrong]=useState(false),[moving,setMoving]=useState<'everyday'|'surprises'|null>(null),[nudge,setNudge]=useState(false),[reviewed,setReviewed]=useState(false),[finished,setFinished]=useState<Budget|null>(null),[adding,setAdding]=useState(false),[mainGroup,setMainGroup]=useState('Home & bills');
 const [audioReady,setAudioReady]=useState(preview);
 useEffect(()=>{if(preview)return;return warmPipAudio([0,1],currency,()=>setAudioReady(true));},[preview]);
 useEffect(()=>{if(step<2||step>=14||muted)return;return warmPipAudio([step,...Array.from({length:14-step},(_,i)=>step+i+1).filter(s=>s<14&&s!==13)],currency);},[step,currency,muted]);
 const [saving,setSaving]=useState(false),[locked,setLocked]=useState(false);const pendingBudget=useRef<Budget|null>(null),savingRef=useRef(false);
 const audio=useRef<HTMLAudioElement>(null),music=useRef<HTMLAudioElement>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null),lastActivity=useRef(Date.now()),nudged=useRef(false),currentStep=useRef(step),soundOff=useRef(muted),currencyRef=useRef(currency);
 currentStep.current=step;soundOff.current=muted;currencyRef.current=currency;
 const format=(n:number)=>money(n,currency).replace(/\.00$/,'');
 const categories=[...suggestions.filter(c=>selected.includes(c.name)),...custom];
 let opening=0,assigned=0,validPlan=true;
 try{opening=cents(balance||'0');for(const c of categories){const value=cents(amounts[c.id]||'0');if(value<0)validPlan=false;assigned+=value;}}catch{validPlan=false;}
 const left=opening-assigned;
 function playClip(index:number,force=false){if(!preview&&[13,14,17].includes(index)){audio.current?.pause();return;}const player=audio.current;if(!player)return;player.pause();setSpeaking(false);setAudioError(false);setBlocked(false);player.src=pipAudioUrl(index,currencyRef.current);if(force){setMuted(false);soundOff.current=false;}if(!soundOff.current&&!document.hidden){if(music.current){music.current.volume=.035;void music.current.play().catch(()=>{});}void player.play().catch(cause=>{if(cause.name==='NotAllowedError')setBlocked(true);else if(cause.name!=='AbortError')setAudioError(true);});}}
 function activity(){lastActivity.current=Date.now();setNudge(false);}
 function go(index:number){window.scrollTo({top:0,behavior:'instant'});if(timer.current)clearTimeout(timer.current);activity();nudged.current=false;setMoving(null);setStep(index);currentStep.current=index;setError('');setWrong(false);setAdding(false);setReviewed(false);if(index<18)playClip(index);else{audio.current?.pause();music.current?.pause();}}
 useEffect(()=>{const interval=setInterval(()=>{if(document.hidden||currentStep.current===0||currentStep.current>=14||nudged.current||!audio.current?.paused)return;if(Date.now()-lastActivity.current>25000){nudged.current=true;setNudge(true);playClip(19);}},1000);function visibility(){audio.current?.pause();music.current?.pause();lastActivity.current=Date.now();}document.addEventListener('visibilitychange',visibility);return()=>{clearInterval(interval);document.removeEventListener('visibilitychange',visibility);if(timer.current)clearTimeout(timer.current);audio.current?.pause();music.current?.pause();};},[]);
 useEffect(()=>{if(music.current)music.current.volume=speaking?.035:.065;},[speaking]);
 function sound(){if(step>=18){setMuted(!muted);audio.current?.pause();music.current?.pause();return;}if(muted){setMuted(false);playClip(step,true);}else{setMuted(true);soundOff.current=true;audio.current?.pause();music.current?.pause();}}
 function fillEnvelope(kind:'everyday'|'surprises'){if(moving)return;setMoving(kind);timer.current=setTimeout(()=>go(kind==='everyday'?3:4),750);}
 function nextForm(){if(step===8&&!budgetName.trim()){setError('Give your budget a name.');return;}if(step===9&&!account.trim()){setError('Give your account a name.');return;}if(step===10){try{if(cents(balance)<0)throw Error();}catch{setError('Enter a balance of zero or more, with up to two decimals.');return;}}go(step+1);}
 async function finish(){if(savingRef.current)return;savingRef.current=true;setSaving(true);setError('');try{if(!reviewed)throw Error('Confirm that you have reviewed the amounts.');if(!pendingBudget.current){if(!validPlan||left!==0)throw Error('Give all your available money a purpose first.');let b:Budget={...blankBudget(currency),name:budgetName.trim(),categories,accounts:[{id:id(),name:account.trim(),type:accountType,opening,date:today(),lastFour:''}]};for(const c of categories){const value=cents(amounts[c.id]||'0');if(value)b=allocate(b,'ready',c.id,value,today());}pendingBudget.current=validateBudget(b);setLocked(true);}if(!preview){if(!onSave)throw Error('Budget saving is unavailable.');await onSave(pendingBudget.current);}setFinished(pendingBudget.current);setLocked(false);go(14);}catch(e){setError((e instanceof Error?e.message:'Could not save your budget.')+' Your draft is kept. Retry to confirm the same budget.');}finally{savingRef.current=false;setSaving(false);}}
 function exportDraft(){if(!pendingBudget.current)return;const url=URL.createObjectURL(new Blob([JSON.stringify(pendingBudget.current,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='spenton-setup-draft.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

 const heading=step===18?'':step===19?budgetName:step===17?'You’re ready to explore.':step===2?'Keep '+format(70000)+' for everyday needs.':step===3?'Keep '+format(30000)+' for surprises.':step===6?'Groceries. '+format(10000)+'.':headings[step];
 const cta=(label:string,target:number)=> <button className="story-action" onClick={()=>go(target)}>{label}<ArrowRight size={17}/></button>;
 function table(demo=false){const rows=demo?[{id:'needs',name:'Everyday needs',group:'Categories',amount:step===7?60000:70000},{id:'surprises',name:'Surprises',group:'Categories',amount:30000}]:categories.map(c=>({...c,amount:cents(amounts[c.id]||'0')}));return <div className="budget-table"><div className="budget-table-head"><span>Category</span><span>Set aside</span><span>Spent</span><span>Left</span></div>{[...new Set(rows.map(c=>c.group))].map(group=><section key={group}><h3>{group}</h3>{rows.filter(c=>c.group===group).map(c=><button type="button" className={'budget-table-row '+(step===6&&c.id==='needs'?'category-prompt':'')} key={c.id} disabled={step!==6} onClick={()=>{if(c.id==='needs')go(7);else{setWrong(true);playClip(18);}}}><span><ShoppingBasket size={16}/>{c.name}</span><span>{format(c.amount+(demo&&step===7&&c.id==='needs'?10000:0))}</span><span>{format(demo&&step===7&&c.id==='needs'?10000:0)}</span><strong>{format(c.amount)}</strong></button>)}</section>)}</div>;}
 return <main className="pip-review" data-speaking={speaking} data-nudge={nudge} onPointerDown={activity} onKeyDown={activity}>
  <audio ref={music} src="/audio/pip/pip-garden.mp3" loop preload="none" aria-hidden="true"/><audio ref={audio} onPlay={()=>setSpeaking(true)} onPause={()=>setSpeaking(false)} onEnded={()=>{setSpeaking(false);lastActivity.current=Date.now();if(currentStep.current===0&&started)go(1);}} onError={()=>{setAudioError(true);setSpeaking(false);if(currentStep.current===0&&started)go(1);}}/>
  <header className="story-topbar"><a href={preview?"/pip-review.html":"/app"} onClick={e=>{if(!preview)e.preventDefault();}}><img src="/brand/spenton-symbol.svg" alt=""/>SpentOn<span>with Pip</span></a><div className="story-tools"><span className="review-tag">{testMode?"Owner test · separate budget":preview?"Design review · not saved":"Your first budget"}</span>{onImport&&!locked&&step<14&&<button className="text-action" onClick={onImport}>Import a backup</button>}{onClose&&!locked&&step<14&&<button className="text-action" onClick={onClose}>Set up later</button>}<button className="round-control" aria-label={muted?'Turn Pip’s voice on':'Turn Pip’s voice off'} aria-pressed={!muted} onClick={sound}>{muted?<VolumeX size={19}/>:<Volume2 size={19}/>}</button></div></header>
  <div className="story-progress" aria-label={step<8?'The idea':'Your budget'}><span style={{width:Math.min(100,step/14*100)+'%'}}/></div>
  <section className="story-stage">
   {step>0&&step<14&&!locked&&<button className="story-back" aria-label="Previous step" onClick={()=>go(step===8?5:step-1)}><ArrowLeft size={18}/></button>}
   <header className="story-heading" key={step}><span className="story-kicker">{step===0?'MEET YOUR MONEY COMPANION':step===1?'MAKE IT FAMILIAR':step<5?'THE ENVELOPE IDEA':step<8?'IN SPENTON · EXAMPLE':step<14?'YOUR FIRST BUDGET': 'EXPLORE AT YOUR OWN PACE'}</span>{heading&&<h1>{heading}</h1>}{step===0&&<p>{cues[0]}</p>}</header>
   {step===0&&<div className="hello-scene"><div className="hello-orbit orbit-one"><Wallet size={22}/></div><div className="hello-orbit orbit-two"><ShoppingBasket size={22}/></div><div className="hello-orbit orbit-three"><Sparkles size={22}/></div><div className="pip-companion hello-pip" data-mood="wave"><span className="pip-art" aria-hidden="true" dangerouslySetInnerHTML={{__html:pipArtwork}}/></div><div className="hello-shadow"/>{!started?<button className="story-action" disabled={!audioReady} onClick={()=>{setStarted(true);if(muted)go(1);else playClip(0);}}>{audioReady?"Start with Pip":"Getting Pip ready…"}<ArrowRight size={18}/></button>:<button className="text-action" onClick={()=>go(1)}>Skip greeting</button>}<small>Turn on your speakers or use headphones to hear Pip guide you. You can also follow along without sound.</small></div>}
   {step===1&&<div className="currency-scene"><div className="currency-grid">{currencies.map(([code,label])=><button key={code} aria-pressed={currency===code} onClick={()=>setCurrency(code)}><strong>{code}</strong><span>{label}</span>{currency===code&&<Check size={16}/>}</button>)}</div>{cta('Use '+currency,2)}<small>This will also be your budget’s currency.</small></div>}
   {step>=2&&step<=4&&<div className="cash-scene"><div className="cash-total"><Wallet size={18}/><span>{step===4?'Still your money':'Example · Available to plan'}</span><strong>{format(step===3?30000:100000)}</strong></div><div className="envelope-row">{moving&&<div className={'flying-cash fly-'+moving}>{format(moving==='everyday'?70000:30000)}</div>}<Envelope kind="everyday" value={step>=3?70000:0} active={step===2&&!moving} filled={step>=3} onClick={()=>fillEnvelope('everyday')} format={format}/><Envelope kind="surprises" value={step===4?30000:0} active={step===3&&!moving} filled={step===4} onClick={()=>fillEnvelope('surprises')} format={format}/></div>{step===4&&cta('See it in SpentOn',5)}</div>}
   {step>=5&&step<=7&&<><div className="mini-app"><div className="mini-app-bar"><span><span className="mini-logo">s.</span>My everyday budget</span><span>Example · {currency}</span></div><div className="mini-app-body"><aside aria-hidden="true"><Home size={18}/><Wallet size={18}/></aside><div className="mini-main"><div className="budget-toolbar"><div><small>Available to plan</small><strong>{format(0)}</strong></div>{step===5&&<button className="small-action" onClick={()=>go(8)}>Plan your money<ArrowRight size={15}/></button>}</div>{table(true)}{wrong&&<p className="practice-error" role="status">A surprise at checkout? Maybe. Groceries go in Everyday needs.</p>}</div></div></div>{step===5&&<button className="text-action" onClick={()=>go(6)}>Show a {format(10000)} purchase first</button>}{step===7&&cta('Set up my budget',8)}</>}
   {step>=8&&step<=10&&<div className="question-scene"><div className="question-icon"><Wallet size={27}/></div><form onSubmit={e=>{e.preventDefault();nextForm();}}><label htmlFor="setup-answer">{step===8?'Budget name':step===9?'Account name':'Current balance in '+account}</label><div className={'single-answer '+(step<10?'name-answer':'')}>{step===10&&<span className="currency-prefix">{currency}</span>}<input autoFocus key={step} id="setup-answer" autoComplete="off" inputMode={step===10?'decimal':'text'} value={step===8?budgetName:step===9?account:balance} onChange={e=>{if(step===10&&!isAmountInput(e.target.value))return;(step===8?setBudgetName:step===9?setAccount:setBalance)(e.target.value);setError('');}} placeholder={step===8?'My everyday budget':step===9?'e.g. Salary account':'0.00'} maxLength={step===10?20:80}/></div>{step===9&&<><fieldset className="account-type-cards"><legend>Account type</legend>{[['checking','Current account or cash','For everyday spending'],['savings','Savings account','Money you keep for later']].map(([value,label,hint])=><label key={value}><input type="radio" name="account-type" checked={accountType===value} onChange={()=>setAccountType(value as 'checking'|'savings')}/><span><strong>{label}</strong><small>{hint}</small></span>{accountType===value&&<Check size={17}/>}</label>)}</fieldset><p className="short-hint">An account tracks where money is held. Add your other accounts later.</p></>}{step===10&&<p className="short-hint">Balance as of {today()}. Zero is okay.</p>}<button className="story-action">{step===10?'Choose categories':'Continue'}<ArrowRight size={17}/></button></form></div>}
   {step===11&&<div className="category-picker"><div className="starter-grid">{[...new Set(suggestions.map(c=>c.group))].map(group=><fieldset key={group}><legend>{group}</legend>{suggestions.filter(c=>c.group===group).map(c=><label key={c.id}><input type="checkbox" checked={selected.includes(c.name)} onChange={e=>setSelected(e.target.checked?[...selected,c.name]:selected.filter(n=>n!==c.name))}/>{c.name}</label>)}</fieldset>)}</div>{custom.map(c=><div className="custom-category" key={c.id}>{c.group} / {c.name}<button aria-label={'Remove '+c.name} onClick={()=>setCustom(custom.filter(x=>x.id!==c.id))}>Remove</button></div>)}<button className="text-action" onClick={()=>{setAdding(!adding);if(!adding)playClip(20);}}><Plus size={15}/>Add a category</button>{adding&&<form className="add-category-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),name=String(f.get('category')).trim(),group=mainGroup.trim();if(!name||!group||[...suggestions,...custom].some(c=>c.name.toLowerCase()===name.toLowerCase())){setError('Choose a new category name and a main category.');return;}setCustom([...custom,{id:id(),name,group,icon:'basket',color:'sage',target:0,targetType:'monthly'}]);setAdding(false);setError('');}}><div className="main-category-choice"><span>Main category</span><div>{[...new Set([...suggestions,...custom].map(c=>c.group))].map(g=><button type="button" key={g} aria-pressed={mainGroup===g} onClick={()=>setMainGroup(g)}>{g}{mainGroup===g&&<Check size={12}/>}</button>)}</div><label>Or name a new main category<input name="group" value={mainGroup} onChange={e=>setMainGroup(e.target.value)} placeholder="e.g. Home" maxLength={60} required/></label></div><label>Subcategory<input name="category" placeholder="e.g. Repairs" maxLength={80} required/></label><button className="small-action">Add category</button></form>}<p className="short-hint">Home is a main category. Rent and Utilities sit underneath it.</p><button className="story-action" onClick={()=>{if(!categories.length){setError('Choose at least one category.');return;}go(12);}}>Plan your money<ArrowRight size={17}/></button></div>}
   {step===12&&<div className="plan-scene"><div className="budget-toolbar"><div><small>Available to plan</small><strong className={left<0?'overplanned':''}>{validPlan?format(left):'Check amounts'}</strong></div><span>{left===0&&validPlan?<><Check size={16}/> Every unit has a purpose</>:'Choose an amount for each purpose'}</span></div><form onSubmit={e=>{e.preventDefault();if(!validPlan||left!==0){setError(left<0?'You have set aside more than your balance. Reduce an amount.':'Set aside the remaining money, including anything you want to save.');return;}go(13);}}>{[...new Set(categories.map(c=>c.group))].map(group=><fieldset className="plan-group" key={group}><legend>{group}</legend>{categories.filter(c=>c.group===group).map(c=><label key={c.id}><span>{c.name}</span><span>{currency}<AmountInput aria-label={'Plan for '+c.name} inputMode="decimal" placeholder="0.00" value={amounts[c.id]||''} onChange={e=>{if(!isAmountInput(e.target.value))return;setAmounts({...amounts,[c.id]:e.target.value});setError('');}}/></span></label>)}</fieldset>)}{opening===0&&<p className="short-hint">No money to plan yet. Keep these categories ready for your next income.</p>}<button className="story-action">Review my budget<ArrowRight size={17}/></button></form></div>}
   {step===13&&<div className="review-budget"><div className="review-identity"><h2>{budgetName}</h2><span>{currency}</span><button className="text-action" disabled={locked} onClick={()=>go(8)}>Edit name</button></div><div className="review-account"><Wallet size={18}/><span>{account}<small>{accountType==='savings'?'Savings':'Checking / current / cash wallet'} · {today()}</small></span><strong>{format(opening)}</strong><button className="text-action" disabled={locked} onClick={()=>go(9)}>Edit account</button></div>{table()}<button className="text-action" disabled={locked} onClick={()=>go(11)}>Edit categories and amounts</button><label className="review-confirm"><input type="checkbox" disabled={locked} checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>I’ve checked my account balance and category amounts.</label><button className="story-action" disabled={!reviewed||saving} onClick={()=>void finish()}>{saving?"Saving your budget…":locked?"Retry saving budget":preview?"Finish preview":"Create my budget"}<Check size={17}/></button><p className="short-hint">{preview?"In the live flow, this final action will create your budget.":"Your account, categories, and plan will be saved together."}</p>{locked&&!saving&&<button className="text-action" onClick={exportDraft}>Download my draft</button>}</div>}
   {step===14&&<div className="completion-scene"><div className="complete-check"><Check size={35}/></div><p>{finished?.name} · {format(finished?calculate(finished,thisMonth()).cash:0)} given a purpose</p><div className="next-choices"><button onClick={()=>go(15)}><ShoppingBasket size={21}/><strong>Something you spent today?</strong><span>See Add transaction</span></button><button onClick={()=>go(16)}><Sparkles size={21}/><strong>Saving for something?</strong><span>See how goals work</span></button></div><button className="story-action" onClick={()=>go(18)}>I’ll explore on my own<ArrowRight size={17}/></button></div>}
   {step===15&&<div className="optional-card"><h2>Add transaction</h2><div className="transaction-example"><span>Account</span><strong>{account}</strong><span>Category</span><strong>{categories[0]?.name}</strong><span>Amount</span><strong>What you spent</strong></div><p>Choose the account, choose a category, enter the amount, then click Save transaction.</p><p className="short-hint">Your opening balance should be from before a purchase you record.</p>{cta('I can add this later',14)}</div>}
   {step===16&&<div className="optional-card"><Sparkles size={32}/><h2>A goal for your next holiday?</h2><p>Open a category and set a goal. SpentOn helps you see how much to save.</p><p className="short-hint">Then use Plan your money to set the money aside.</p>{cta('Got it',14)}</div>}
   {step===18&&<OnboardingFeedback preview={preview} testMode={testMode} onSubmit={onFeedback} onContinue={()=>preview?go(19):onComplete?.()}/>}
   {step===19&&<div className="review-budget"><div className="budget-toolbar"><div><small>Available to plan</small><strong>{format(0)}</strong></div><span><Check size={16}/>Your budget preview</span></div>{table()}<p className="short-hint">This is where you’ll return to plan your money and check what’s left.</p><p className="short-hint">Design preview only. No budget or feedback was saved.</p></div>}
   {step===17&&<div className="completion-scene"><div className="pip-companion hello-pip" data-mood="relieved"><span className="pip-art" aria-hidden="true" dangerouslySetInnerHTML={{__html:pipArtwork}}/></div><p>This welcome is designed for your first budget only.</p><button className="text-action" onClick={()=>go(14)}>Back to my next steps</button></div>}
   {error&&<p className="practice-error" role="alert">{error}</p>}
  </section>
  {step>0&&step<17&&<footer className="pip-narrator"><div className="pip-companion guide-character" data-mood={speaking?'wave':'idle'}><span className="pip-art" aria-hidden="true" dangerouslySetInnerHTML={{__html:pipArtwork}}/></div><div className="pip-caption"><span>PIP {speaking&&!muted&&<i className="voice-wave" aria-label="Pip is speaking"><b/><b/><b/><b/></i>}</span><p aria-live="polite">{nudge?'Ready when you are. '+cues[step]:cues[step]}</p></div><button className="round-control" aria-label="Hear that again" onClick={()=>playClip(step,true)}><RotateCcw size={16}/></button></footer>}
  {(blocked||audioError)&&<button className="voice-retry" onClick={()=>playClip(step,true)}>{audioError?'Retry voice':'Enable Pip’s voice'}<Volume2 size={14}/></button>}
  <div className="story-footnote">{testMode?"Owner test. Your everyday budgets and customer feedback stay unchanged.":preview?"Design review. Entries stay on this page and are not saved.":"Pip is your AI-voiced guide. Your budget is private."}</div>
 </main>;
}
