import { describe, expect, it } from 'vitest';
import { allocate, blankBudget, calculate, validateBudget } from './engine';
import type { Budget, Entry, Schedule } from './engine';
import { nextOccurrence, postOccurrence } from './recurring';
const expense:Entry={id:'purchase',date:'2026-01-31',kind:'expense',amount:10000,accountId:'card',payee:'Shop',note:'',cleared:true,splits:[{categoryId:'groceries',amount:6000},{categoryId:'dining',amount:4000}]};
function base():Budget{return {...blankBudget(),accounts:[{id:'cash',name:'Cash',type:'checking',opening:100000,date:'2026-01-01',lastFour:''},{id:'card',name:'Card',type:'credit',opening:0,date:'2026-01-01',lastFour:''}],entries:[]};}
const schedule:Schedule={id:'monthly',frequency:'monthly',nextDate:'2026-01-31',template:expense};
const conserved=(b:Budget)=>{const t=calculate(b,'2026-01');expect(t.cash).toBe(t.unassignedBeforeShortfalls+Object.values(t.categories).reduce((n,c)=>n+c.cash,0)+Object.values(t.cards).reduce((n,c)=>n+c.reserve,0));expect(t.cash).toBe(t.ready+Object.values(t.categories).reduce((n,c)=>n+Math.max(0,c.cash),0)+Object.values(t.cards).reduce((n,c)=>n+Math.max(0,c.reserve),0));};
describe('split purchases',()=>{
 it('funds each card category independently and counts the purchase once',()=>{let b=allocate(base(),'ready','groceries',6000,'2026-01-01');b=validateBudget({...b,entries:[...b.entries,expense]});const t=calculate(b,'2026-01');expect(t.spent).toBe(10000);expect(t.balances.card).toBe(-10000);expect(t.cards.card.reserve).toBe(6000);expect(t.categories.dining.available).toBe(-4000);expect(t.categories.groceries.spent).toBe(6000);expect(t.transactions).toHaveLength(1);conserved(b);});
 it('debits cash once, supports editing, and preserves split data in backups',()=>{const b=validateBudget({...base(),entries:[{...expense,accountId:'cash'}]});expect(calculate(b,'2026-01').cash).toBe(90000);conserved(b);expect(validateBudget(JSON.parse(JSON.stringify(b))).entries[0].splits).toEqual(expense.splits);const edited=validateBudget({...b,entries:[{...expense,accountId:'cash',amount:5000,splits:[{categoryId:'groceries',amount:2000},{categoryId:'dining',amount:3000}]}]});expect(calculate(edited,'2026-01').cash).toBe(95000);conserved(edited);});
 it('rejects mismatched totals, unknown categories, mixed category fields and splits on income',()=>{for(const edit of [{amount:9999},{splits:[{categoryId:'missing',amount:6000},{categoryId:'dining',amount:4000}]},{categoryId:'groceries'},{kind:'income',accountId:'cash'}])expect(()=>validateBudget({...base(),entries:[{...expense,...edit}]})).toThrow();});
});
describe('recurring entries',()=>{
 it('clamps February and returns to the original month-end day',()=>{expect(nextOccurrence(schedule)).toBe('2026-02-28');expect(nextOccurrence({...schedule,nextDate:'2026-02-28'})).toBe('2026-03-31');expect(nextOccurrence({...schedule,frequency:'weekly'})).toBe('2026-02-07');});
 it('handles leap-day yearly recurrence',()=>{const s={...schedule,frequency:'yearly' as const,nextDate:'2024-02-29',template:{...expense,date:'2024-02-29'}};expect(nextOccurrence(s)).toBe('2025-02-28');expect(nextOccurrence({...s,nextDate:'2027-02-28'})).toBe('2028-02-29');});
 it('keeps scheduled income out of balances and records only a due occurrence',()=>{const s={...schedule,template:{...expense,kind:'income' as const,accountId:'cash',splits:undefined}};const b=validateBudget({...base(),schedules:[s]});expect(calculate(b,'2026-01').income).toBe(0);expect(()=>postOccurrence(b,s.id,'2026-01-30')).toThrow(/not due/);const next=postOccurrence(b,s.id,'2026-01-31');expect(calculate(next,'2026-01').income).toBe(10000);expect(next.entries[0].cleared).toBe(false);expect(next.schedules![0].nextDate).toBe('2026-02-28');expect(()=>postOccurrence(next,s.id,'2026-01-31')).toThrow(/not due/);});
 it('does not duplicate an already posted occurrence and validates templates',()=>{const b=postOccurrence({...base(),schedules:[schedule]},schedule.id,'2026-01-31');const retry=postOccurrence({...b,schedules:[schedule]},schedule.id,'2026-01-31');expect(retry.entries).toHaveLength(1);expect(()=>validateBudget({...base(),schedules:[{...schedule,template:{...expense,accountId:'missing'}}]})).toThrow();});
});
